
export const dataCursos = [
    {
        id: 1,
        title: "Curso de React.",
        Precio: "C$ 300.",
        nivel: "Nivel principiante.",
        imagen: "https://www.datocms-assets.com/45470/1631110818-logo-react-js.png",
        link1:"https://www.youtube.com/watch?v=2SwKpVVNfIE",
        link2:"https://www.youtube.com/watch?v=", 
        link3:"https://youtu.be/EJzX4XSpZFg?si=c5tWBxZIwtuhWOGI",
        instructor:"Carpi Coder",
        horas:"40",
        descripcion:"Aprende a crear aplicaciones web con react js en este curso.",
        tema1:"instalación",
        tema2:"componentes",
        tema3:"props",
    },
    {
        id: 2,
        title: "Curso de Angular.",
        Precio: "C$ 300.",
        nivel: "Nivel principiante.",
        imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/512px-Angular_full_color_logo.svg.png",
        link1:"https://www.youtube.com/watch?v=6741ceWzsKQ",
        link2:"https://www.youtube.com/watch?v=", 
        link3:"https://youtu.be/EJzX4XSpZFg?si=c5tWBxZIwtuhWOGI",
        horas:"45",
        descripcion:"Aprende a crear aplicaciones web con Angularjs en este curso.",
        tema1:"instalación",
        tema2:"componentes",
        tema3:"comnicación de componentes",
    },
    {
        id: 3,
        title: "Curso de backend con nestjs",
        Precio: "C$ 300.",
        nivel: "Nivel principiante.",
        imagen: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/NestJS.svg/1200px-NestJS.svg.png",
        link1:"https://www.youtube.com/watch?v=lonpW-0EybY",
        link2:"https://www.youtube.com/watch?v=", 
        link3:"https://youtu.be/EJzX4XSpZFg?si=c5tWBxZIwtuhWOGI",
        instructor:"Leifer Medez",
        horas:"30",
        descripcion:"Aprende a crear APIs, cruds y microservicios con nestjs.",
        tema1:"Intraduccion al backend",
        tema2:"Qué es una API",
        tema3:"Crontollers y Services",
    },
]